require:
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "**/*_pb.rb"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
